### ISSUE TITLE
Musket Doesn't Reload When Player Dies While Holding It

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#719]

**Comment by iwek7** [comment]
I looked at it a bit and reason is pretty simple. Musket is updating before damage system kills player and adds musket to dropped items list. Then `throw_dropped_items` system removes musket from dropped items so that this condition in musket update system is never triggered when it is evaluated next frame:
```
  if items_dropped.get(entity).is_some() {
            // reload gun
            musket.ammo = *max_ammo;
        }
```
