### ISSUE TITLE
AI players respawn with their weapon

### ISSUE THREAD

**Issue by alberic89** [fishfolk/jumpy#796]
When an AI player dies, he respawns with his weapon in his hand, but not the normal player.

**Comment by zicklag** [comment]
That was a temporary solution due to the fact that AI aren't smart enough to:

1. wield any weapon other than a sword, and 
2. find weapons on the map and pick them up.

We could probably implement finding and picking up weapons easy enough, since we already have them smart enough to pathfind, but not every map comes with a sword.

We could spawn as many swords as there are players, on every map that you play with the AI, to make sure there would be enough swords for the AI. Does that seem like a good idea?

I'm going to work first on #787, but I could come to this after that.

**Comment by erlend-sh** [comment]
That’d be fixing our workaround with another workaround, heh. For our next AI iteration following the playability tweaks I’d rather go straight to general weapon pick-up & usage.

That’s not as high priority as the docs about our core tech though, so just make a help-wanted issue for advanced AI and share some best guesses on next steps for prospective contributors.

**Comment by zicklag** [comment]
OK, I'll close this in favor of #675, then.
