### ISSUE TITLE
Puffin Profiler Turned Off

### ISSUE THREAD

**Issue by zicklag** [fishfolk/jumpy#831]
### Description

When starting the puffin profiler in the game it says:

```
The puffin profiler is OFF!
No profiling data.
```

### To Reproduce

Start the game and press `f7` to show the profiling window.

### Expected Behavior

The profiling window should show the profiling data being recorded.

### Additional Context

This used to work, so I'm not sure what changed. Maybe we update the puffin version or something.

You're supposed to use `puffin::set_scopes_on(true)` in order to start the profiler, and we do that here, where we turn the scopes on, but only if the window is showing.

https://github.com/fishfolk/jumpy/blob/241d080be6e6a80f4d283d4a31633826ac1dd242/src/ui/debug_tools.rs#L248

I tested just changing that to `true` instead of `show.profiler`, but it's still not working for some reason.

**Comment by MaxCWhitehead** [comment]
It seems the issue here is that we updated puffin to 0.16, but did not upgrade puffin_egui to 0.22 (these versions were bumped together). 

We likely did not upgrade puffin_egui because this causes a compilation error, as bevy_egui is still using dep egui 0.21 (while puffin_egui is at 0.22), types mismatch.

Simplest solution here is to downgrade puffin to 0.15 which fixes it. Can upgrade puffin crates once bevy_egui has a release with egui 0.22. I can open a PR later (or feel free to do it) if that sounds good.
