### ISSUE TITLE
AI clipping into collision boxes and losing control of the player

### ISSUE THREAD

**Issue by Biped-Potato** [fishfolk/jumpy#882]
### Description

Context: The player controlled character is "Fishy" the orange one, every other entity is an AI
1. AI Clipping issue
The AI will occasionally clip into the ground and start repeatedly playing the jump sound resulting in an obnoxious jittering noise while creating a motion as seen in the video
2. Player Control Loss
The ability to control the player is often lost for a period of time where it will just move to the right(i've only experienced to the right). You can stop this movement but not move in the other direction by pressing the left key.

https://github.com/fishfolk/jumpy/assets/79812179/7c41172a-8a1d-4d84-be5d-ce16ee7f0d70

### To Reproduce

After moving around for a while these errors both occur for me

**Comment by zicklag** [comment]
Thanks for the report!

Just for reference, I believe that the issue with the AI getting stuck is a physics issue related to https://github.com/fishfolk/jumpy/issues/853 and the player issue will require more investigation.

No need for action on your part, I'll probably tackle this after getting networking back into MVP state.

**Comment by zicklag** [comment]
I figured out the input issue! I'm pretty sure, anyway, let me know if you have issues after the next release. I know I fixed _something_, and I'm pretty sure it helps a lot with the controls. Random inputs were being dropped or delayed 'till the next frame because of a missing ordering constraint in the Bevy system.

Fix is incoming, and I'll publish a bugfix release that includes both of the latest fixes.
