### ISSUE TITLE
Spike Shoes are still in player's hand after equipping

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/jumpy#929]
### Description

After equipping spike shoe they are still in the player's hand and may be dropped, while remaining on player's feet.

### To Reproduce

Pickup spike shoe (Level 3 should have some).

### Expected Behavior

Spike shoe should be consumed once equipped?

**Comment by Breadp4ck** [comment]
The item is called Stomp Boots. So, we may either drop or despawn them.

In the first approach, if the player also has a hat, there will be two (or three!) items left at the death location, which is not very convenient. We can solve this by giving either boots or hat some inertia for easier picking up. But I think that will be a little bit messy anyway.

I prefer the second approach. However, it may be not very enjoyable, since players won't be able to pick up the boots of the player they've slain.

To implement that, there must be some systems which despawn `Attachment`s or something? I want to try to do something.
